import = ["~/.config/alacritty/themes/themes/carbonfox.toml"]

[env]
TERM = "xterm-256color"

[font.bold]
family = "Mononoki Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Mononoki Nerd Font"
style = "SemiBold"

[font.italic]
family = "Mononoki Nerd Font"
style = "Light"

[font.normal]
family = "Mononoki Nerd Font"
style = "Regular"

[window]
decorations = "full"
opacity = 0.8
